export enum RABBIT_MQ_QUEUES {
    MESSAGES_TO_TELEGRAM_QUEUE = 'MESSAGES_TO_TELEGRAM_QUEUE',
    ORDERS_TRACKING_QUEUE = 'ORDERS_TRACKING_QUEUE',
    PERSONAL_DISCOUNT_INPUT_QUEUE = 'PERSONAL_DISCOUNT_INPUT_QUEUE',
    PERSONAL_DISCOUNT_CHUNK_QUEUE = 'PERSONAL_DISCOUNT_CHUNK_QUEUE',
    PERSONAL_DISCOUNT_PRODUCT_QUEUE = 'PERSONAL_DISCOUNT_PRODUCT_QUEUE',
    ACCOUNT_SHORT_INFO_QUEUE = 'ACCOUNT_SHORT_INFO_QUEUE',
}

export const RABBIT_MQ_QUEUES_LIST = Object.values(RABBIT_MQ_QUEUES);
