export enum RABBIT_MQ_QUEUES {
    MESSAGES_TO_TELEGRAM_QUEUE = 'MESSAGES_TO_TELEGRAM_QUEUE',
    ORDERS_TRACKING_QUEUE = 'ORDERS_TRACKING_QUEUE',
}

export const RABBIT_MQ_QUEUES_LIST = Object.values(RABBIT_MQ_QUEUES);
